#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disposable.Web.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc.Html;


#line 1 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
    using Microsoft.Web.WebPages.OAuth;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/_ExternalLoginsListPartial.cshtml")]
    public partial class ExternalLoginsListPartial : System.Web.Mvc.WebViewPage<ICollection<AuthenticationClientData>>
    {
        public ExternalLoginsListPartial()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
 if (Model.Count == 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"message-info\"");

WriteLiteral(">\r\n        <p>There are no external authentication services configured. See <a");

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkId=252166\"");

WriteLiteral(">this article</a>\r\n        for details on setting up this ASP.NET application to " +
"support logging in via external services.</p>\r\n    </div>\r\n");

            
            #line 10 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
}
else
{
    using (Html.BeginForm("ExternalLogin", "Account", new { ReturnUrl = ViewBag.ReturnUrl }))
    {
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                            

            
            #line default
            #line hidden
WriteLiteral("    <fieldset");

WriteLiteral(" id=\"socialLoginList\"");

WriteLiteral(">\r\n        <legend>Log in using another service</legend>\r\n        <p>\r\n");

            
            #line 19 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
        
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
         foreach (AuthenticationClientData p in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" name=\"provider\"");

WriteAttribute("value", Tuple.Create(" value=\"", 777), Tuple.Create("\"", 821)
            
            #line 21 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
, Tuple.Create(Tuple.Create("", 785), Tuple.Create<System.Object, System.Int32>(p.AuthenticationClient.ProviderName
            
            #line default
            #line hidden
, 785), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 822), Tuple.Create("\"", 870)
, Tuple.Create(Tuple.Create("", 830), Tuple.Create("Log", 830), true)
, Tuple.Create(Tuple.Create(" ", 833), Tuple.Create("in", 834), true)
, Tuple.Create(Tuple.Create(" ", 836), Tuple.Create("using", 837), true)
, Tuple.Create(Tuple.Create(" ", 842), Tuple.Create("your", 843), true)
            
            #line 21 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                                        , Tuple.Create(Tuple.Create(" ", 847), Tuple.Create<System.Object, System.Int32>(p.DisplayName
            
            #line default
            #line hidden
, 848), false)
, Tuple.Create(Tuple.Create(" ", 862), Tuple.Create("account", 863), true)
);

WriteLiteral(">");

            
            #line 21 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                                                                                                                                           Write(p.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 22 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        </p>\r\n    </fieldset>\r\n");

            
            #line 25 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
    }
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
