#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disposable.Web.Views.Account
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ExternalLoginFailure.cshtml")]
    public partial class ExternalLoginFailure : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ExternalLoginFailure()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Account\ExternalLoginFailure.cshtml"
  
    ViewBag.Title = "Login Failure";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 6 "..\..\Views\Account\ExternalLoginFailure.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>Unsuccessful login with service.</h2>\r\n</hgroup>\r\n");

        }
    }
}
#pragma warning restore 1591
