#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disposable.Web.Views.Account
{
    using System.Web.Mvc.Html;
    using System.Web.Optimization;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Manage.cshtml")]
    public partial class Manage : System.Web.Mvc.WebViewPage<Disposable.Web.Models.LocalPasswordModel>
    {
        public Manage()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Account\Manage.cshtml"
  
    ViewBag.Title = "Manage Account";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 7 "..\..\Views\Account\Manage.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n</hgroup>\r\n\r\n<p");

WriteLiteral(" class=\"message-success\"");

WriteLiteral(">");

            
            #line 10 "..\..\Views\Account\Manage.cshtml"
                      Write(ViewBag.StatusMessage);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n<p>You\'re logged in as <strong>");

            
            #line 12 "..\..\Views\Account\Manage.cshtml"
                          Write(User.Identity.Name);

            
            #line default
            #line hidden
WriteLiteral("</strong>.</p>\r\n\r\n");

            
            #line 14 "..\..\Views\Account\Manage.cshtml"
 if (ViewBag.HasLocalPassword)
{
    
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Account\Manage.cshtml"
Write(Html.Partial("_ChangePasswordPartial"));

            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Account\Manage.cshtml"
                                           
}
else
{ 
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Account\Manage.cshtml"
Write(Html.Partial("_SetPasswordPartial"));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Account\Manage.cshtml"
                                        
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<section");

WriteLiteral(" id=\"externalLogins\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 24 "..\..\Views\Account\Manage.cshtml"
Write(Html.Action("RemoveExternalLogins"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <h3>Add an external login</h3>\r\n");

WriteLiteral("    ");

            
            #line 27 "..\..\Views\Account\Manage.cshtml"
Write(Html.Action("ExternalLoginsList", new { ReturnUrl = ViewBag.ReturnUrl }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</section>\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 31 "..\..\Views\Account\Manage.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
