#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disposable.Web.Views
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/_ViewStart.cshtml")]
    public partial class ViewStart : System.Web.Mvc.ViewStartPage
    {
        public ViewStart()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\_ViewStart.cshtml"
  
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
