#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disposable.Web2.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Disposable.Web.Mvc;
    using Disposable.Web2;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Index";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 6 "..\..\Views\Home\Index.cshtml"
Write(Html.Disposable(x => x.Component(c => c.Class("william-casey").Class("goodhew"))));

            
            #line default
            #line hidden
WriteLiteral(" </h2>\r\n<h2>");

            
            #line 7 "..\..\Views\Home\Index.cshtml"
Write(Html.Disposable(x => x.Field(f => f.Class("Maria").Label("Sanchez was here"))));

            
            #line default
            #line hidden
WriteLiteral(" </h2>\r\n<h2>");

            
            #line 8 "..\..\Views\Home\Index.cshtml"
Write(Html.Disposable(x => x.TextBox(c => c.Class("Daniela").Label("olivia").Rows(4))));

            
            #line default
            #line hidden
WriteLiteral(" </h2>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
