CREATE OR REPLACE PACKAGE DISPOSABLE.constants
IS

/**********************************************************************
	ANY UNUSED CONSTANTS SHOULD BE MOVED TO THE "DEPRICATED"
	SECTION BELOW SO THAT OLD UPDATE SCRIPTS STILL RUN
**********************************************************************/

TYPE T_OUTPUT_CUR					IS REF CURSOR;

SUBTYPE T_SID						IS NUMBER(10);
SUBTYPE T_GUID						IS RAW(32);
SUBTYPE T_EMAIL						IS VARCHAR2(200);
SUBTYPE T_PASSWORD					IS VARCHAR2(2000);

TYPE T_STRINGS                		IS TABLE OF VARCHAR2(2000) INDEX BY PLS_INTEGER;
TYPE T_NUMBERS                		IS TABLE OF NUMBER(10) INDEX BY PLS_INTEGER;

-- a general use code
UNDEFINED							CONSTANT NUMBER := 0;

SUBTYPE T_BOOLEAN					IS NUMBER;
BOOL_TRUE							CONSTANT T_BOOLEAN := 1;
BOOL_FALSE 							CONSTANT T_BOOLEAN := 0;

SUBTYPE T_ACTIVE					IS NUMBER;
ACTIVE 								CONSTANT T_ACTIVE := 1;
INACTIVE 							CONSTANT T_ACTIVE := 0;

SUBTYPE T_OBJECT_TYPE				IS NUMBER;
OT_APPLICATION						CONSTANT T_OBJECT_TYPE := 1;
OT_CONTAINER						CONSTANT T_OBJECT_TYPE := 2;
OT_WEB_RESOURCE						CONSTANT T_OBJECT_TYPE := 3;
OT_MENU_RESOURCE					CONSTANT T_OBJECT_TYPE := 4;
OT_USER								CONSTANT T_OBJECT_TYPE := 5;
OT_ROLE								CONSTANT T_OBJECT_TYPE := 6;
OT_DEVICE							CONSTANT T_OBJECT_TYPE := 7;

SUBTYPE T_PERMISSION_POLICY			IS NUMBER;
PP_ALLOW							CONSTANT T_PERMISSION_POLICY := 1;
PP_DENY								CONSTANT T_PERMISSION_POLICY := 2;

SUBTYPE T_PERMISSION_TYPE			IS NUMBER;
PT_OBJECT_TYPE						CONSTANT T_PERMISSION_TYPE := 1;
PT_OBJECT							CONSTANT T_PERMISSION_TYPE := 2;
-- PT_XXXX							CONSTANT T_PERMISSION_TYPE := 4;

END constants;
/

