--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      c
-- Project :      disposable.dm1
-- Author :       Casey
--
-- Date Created : Monday, August 26, 2013 00:18:02
-- Target DBMS : MySQL 5.x
--

-- 
-- TABLE: COMMON.ACT 
--

CREATE TABLE COMMON.ACT(
    ACT_ID         INT         NOT NULL,
    APP_ID         INT         NOT NULL,
    USER_ID        INT         NOT NULL,
    ACT_TYPE_ID    INT         NOT NULL,
    ISSUED_DTM     DATETIME    NOT NULL,
    PRIMARY KEY (ACT_ID, APP_ID)
)
;



-- 
-- TABLE: COMMON.ACT_TYPE 
--

CREATE TABLE COMMON.ACT_TYPE(
    ACT_TYPE_ID          INT         NOT NULL,
    EXPIRATION_OFFSET    DATETIME    NOT NULL,
    PRIMARY KEY (ACT_TYPE_ID)
)
;



-- 
-- TABLE: COMMON.APP 
--

CREATE TABLE COMMON.APP(
    APP_ID    INT    AUTO_INCREMENT,
    PRIMARY KEY (APP_ID)
)
;



-- 
-- TABLE: COMMON.DEVICE 
--

CREATE TABLE COMMON.DEVICE(
    APP_ID            INT            NOT NULL,
    DEVICE_ID         INT            NOT NULL,
    DEVICE_TYPE_ID    INT            NOT NULL,
    USER_ID           INT            NOT NULL,
    NAME              VARCHAR(18)    NOT NULL,
    PRIMARY KEY (APP_ID, DEVICE_ID)
)
;



-- 
-- TABLE: COMMON.DEVICE_TYPE 
--

CREATE TABLE COMMON.DEVICE_TYPE(
    DEVICE_TYPE_ID    INT    NOT NULL,
    PRIMARY KEY (DEVICE_TYPE_ID)
)
;



-- 
-- TABLE: COMMON.USER 
--

CREATE TABLE COMMON.USER(
    APP_ID     INT    NOT NULL,
    USER_ID    INT    AUTO_INCREMENT,
    PRIMARY KEY (APP_ID, USER_ID)
)
;



-- 
-- TABLE: COMMON.ACT 
--

ALTER TABLE COMMON.ACT ADD CONSTRAINT FK_ACT_TYPE_ACT 
    FOREIGN KEY (ACT_TYPE_ID)
    REFERENCES COMMON.ACT_TYPE(ACT_TYPE_ID)
;

ALTER TABLE COMMON.ACT ADD CONSTRAINT FK_APP_ACT 
    FOREIGN KEY (APP_ID)
    REFERENCES COMMON.APP(APP_ID)
;

ALTER TABLE COMMON.ACT ADD CONSTRAINT FK_USER_ACT 
    FOREIGN KEY (APP_ID, USER_ID)
    REFERENCES COMMON.USER(APP_ID, USER_ID)
;


-- 
-- TABLE: COMMON.DEVICE 
--

ALTER TABLE COMMON.DEVICE ADD CONSTRAINT FK_APP_DEVICE 
    FOREIGN KEY (APP_ID)
    REFERENCES COMMON.APP(APP_ID)
;

ALTER TABLE COMMON.DEVICE ADD CONSTRAINT FK_DEVICE_TYPE 
    FOREIGN KEY (DEVICE_TYPE_ID)
    REFERENCES COMMON.DEVICE_TYPE(DEVICE_TYPE_ID)
;

ALTER TABLE COMMON.DEVICE ADD CONSTRAINT FK_USER_DEVICE 
    FOREIGN KEY (APP_ID, USER_ID)
    REFERENCES COMMON.USER(APP_ID, USER_ID)
;


-- 
-- TABLE: COMMON.USER 
--

ALTER TABLE COMMON.USER ADD CONSTRAINT FK_APP_USER 
    FOREIGN KEY (APP_ID)
    REFERENCES COMMON.APP(APP_ID)
;


