--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      Disposable Networks
-- Project :      disposable.dm1
-- Author :       Casey
--
-- Date Created : Wednesday, January 08, 2014 00:43:16
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: DISPOSABLE.ACE 
--

CREATE TABLE DISPOSABLE.ACE(
    APP_SID                  NUMBER(38, 0)    NOT NULL,
    ACE_ID                   NUMBER(38, 0)    NOT NULL,
    OBJECT_TYPE_ID           NUMBER(38, 0)    NOT NULL,
    INHERITED_FROM_ACL_ID    NUMBER(38, 0),
    ACL_ID                   NUMBER(38, 0)    NOT NULL,
    PERMISSION_POLICY_ID     NUMBER(38, 0)    NOT NULL,
    PERMISSION_ID            NUMBER(38, 0)    NOT NULL,
    PERMISSION_TYPE_ID       NUMBER(38, 0)    NOT NULL,
    POSITION                 NUMBER(38, 0)    NOT NULL,
    INHERITABLE              NUMBER(38, 0)    NOT NULL
                             CONSTRAINT CHK_ACE_INHERITABLE CHECK (INHERITABLE IN (0, 1)),
    INHERIT_INHERITABLE      NUMBER(38, 0)    NOT NULL
                             CONSTRAINT CHK_ACE_INHERIT_INHERITABLE CHECK (INHERIT_INHERITABLE IN (0, 1)),
    CONSTRAINT PK_ACE PRIMARY KEY (APP_SID, ACE_ID)
)
;



-- 
-- TABLE: DISPOSABLE.ACL 
--

CREATE TABLE DISPOSABLE.ACL(
    APP_SID               NUMBER(38, 0)    DEFAULT SYS_CONTEXT('DISPOSABLE', 'APP') NOT NULL,
    ACL_ID                NUMBER(38, 0)    NOT NULL,
    OBJECT_TYPE_ID        NUMBER(38, 0)    NOT NULL,
    PERMISSION_TYPE_ID    NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK_ACL PRIMARY KEY (APP_SID, ACL_ID, OBJECT_TYPE_ID, PERMISSION_TYPE_ID)
)
;



-- 
-- TABLE: DISPOSABLE.APP 
--

CREATE TABLE DISPOSABLE.APP(
    APP_SID    NUMBER(38, 0)    DEFAULT SYS_CONTEXT('DISPOSABLE', 'APP') NOT NULL,
    CONSTRAINT PK_APP PRIMARY KEY (APP_SID)
)
;



-- 
-- TABLE: DISPOSABLE.APP_OBJECT 
--

CREATE TABLE DISPOSABLE.APP_OBJECT(
    APP_SID       NUMBER(38, 0)    DEFAULT SYS_CONTEXT('DISPOSABLE', 'APP') NOT NULL,
    OBJECT_SID    NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK_APP_OBJECT PRIMARY KEY (APP_SID, OBJECT_SID)
)
;



-- 
-- TABLE: DISPOSABLE.APP_USER 
--

CREATE TABLE DISPOSABLE.APP_USER(
    USER_SID      NUMBER(38, 0)    NOT NULL,
    APP_SID       NUMBER(38, 0)    DEFAULT SYS_CONTEXT('DISPOSABLE', 'APP') NOT NULL,
    OBJECT_SID    NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK_APP_USER PRIMARY KEY (USER_SID, APP_SID, OBJECT_SID)
)
;



-- 
-- TABLE: DISPOSABLE.AUTHORIZABLE_OBJECT 
--

CREATE TABLE DISPOSABLE.AUTHORIZABLE_OBJECT(
    APP_SID       NUMBER(38, 0)    DEFAULT SYS_CONTEXT('DISPOSABLE', 'APP') NOT NULL,
    OBJECT_SID    NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK_AUTHORIZABLE_OBJECT PRIMARY KEY (APP_SID, OBJECT_SID)
)
;



-- 
-- TABLE: DISPOSABLE.CONSTANT 
--

CREATE TABLE DISPOSABLE.CONSTANT(
    SECTION    VARCHAR2(100)    NOT NULL
               CONSTRAINT CHK_CONSTANT_SECTION CHECK (SECTION = UPPER(SECTION)),
    NAME       VARCHAR2(100)    NOT NULL
               CONSTRAINT CHK_CONSTANT_NAME CHECK (NAME = UPPER(NAME)),
    ID         NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK_CONSTANT PRIMARY KEY (SECTION, NAME)
)
;



-- 
-- TABLE: DISPOSABLE.OBJECT 
--

CREATE TABLE DISPOSABLE.OBJECT(
    OBJECT_SID           NUMBER(38, 0)    NOT NULL,
    OBJECT_TYPE_ID       NUMBER(38, 0)    NOT NULL,
    PARENT_OBJECT_SID    NUMBER(38, 0),
    CONSTRAINT PK_OBJECT PRIMARY KEY (OBJECT_SID)
)
;



-- 
-- TABLE: DISPOSABLE.OBJECT_OBJECT_TYPE 
--

CREATE TABLE DISPOSABLE.OBJECT_OBJECT_TYPE(
    OBJECT_TYPE_ID    NUMBER(38, 0)    NOT NULL,
    OBJECT_SID        NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK_OBJECT_OBJECT_TYPE PRIMARY KEY (OBJECT_TYPE_ID, OBJECT_SID)
)
;



-- 
-- TABLE: DISPOSABLE.OBJECT_PERMISSION_BINDER 
--

CREATE TABLE DISPOSABLE.OBJECT_PERMISSION_BINDER(
    APP_SID                     NUMBER(38, 0)    DEFAULT SYS_CONTEXT('DISPOSABLE', 'APP') NOT NULL,
    PRIMARY_OBJECT_TYPE_ID      NUMBER(38, 0)    NOT NULL,
    PRIMARY_OBJECT_SID          NUMBER(38, 0)    NOT NULL,
    SECONDARY_OBJECT_SID        NUMBER(38, 0)    NOT NULL,
    SECONDARY_OBJECT_TYPE_ID    NUMBER(38, 0)    NOT NULL,
    ACL_ID                      NUMBER(38, 0)    NOT NULL,
    PERMISSION_TYPE_ID          NUMBER(38, 0)    NOT NULL
                                CONSTRAINT CHK_OPB_PERMISSION_TYPE_ID CHECK (PERMISSION_TYPE_ID IN (2, 3)),
    CONSTRAINT PK_OBJECT_PERMISSION_BINDER PRIMARY KEY (APP_SID, PRIMARY_OBJECT_TYPE_ID, PRIMARY_OBJECT_SID, SECONDARY_OBJECT_SID, SECONDARY_OBJECT_TYPE_ID)
)
;



-- 
-- TABLE: DISPOSABLE.OBJECT_POOL 
--

CREATE TABLE DISPOSABLE.OBJECT_POOL(
    OBJECT_SID    NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK_OBJECT_POOL PRIMARY KEY (OBJECT_SID)
)
;



-- 
-- TABLE: DISPOSABLE.OBJECT_RELATIONSHIP 
--

CREATE TABLE DISPOSABLE.OBJECT_RELATIONSHIP(
    APP_SID                 NUMBER(38, 0)    DEFAULT SYS_CONTEXT('DISPOSABLE', 'APP') NOT NULL,
    SECONDARY_OBJECT_SID    NUMBER(38, 0)    NOT NULL,
    PRIMARY_OBJECT_SID      NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK_OBJECT_RELATIONSHIP PRIMARY KEY (APP_SID, SECONDARY_OBJECT_SID, PRIMARY_OBJECT_SID)
)
;



-- 
-- TABLE: DISPOSABLE.OBJECT_TYPE 
--

CREATE TABLE DISPOSABLE.OBJECT_TYPE(
    OBJECT_TYPE_ID    NUMBER(38, 0)    NOT NULL,
    DESCRIPTION       VARCHAR2(100)    NOT NULL,
    CONSTRAINT PK_OBJECT_TYPE PRIMARY KEY (OBJECT_TYPE_ID)
)
;



-- 
-- TABLE: DISPOSABLE.OBJECT_TYPE_PERMISSION 
--

CREATE TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION(
    OBJECT_TYPE_ID    NUMBER(38, 0)    NOT NULL,
    PERMISSION_ID     NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK_OBJECT_TYPE_PERMISSION PRIMARY KEY (OBJECT_TYPE_ID, PERMISSION_ID)
)
;



-- 
-- TABLE: DISPOSABLE.OBJECT_TYPE_PERMISSION_BINDER 
--

CREATE TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION_BINDER(
    APP_SID                     NUMBER(38, 0)    DEFAULT SYS_CONTEXT('DISPOSABLE', 'APP') NOT NULL,
    PRIMARY_OBJECT_TYPE_ID      NUMBER(38, 0)    NOT NULL,
    SECONDARY_OBJECT_TYPE_ID    NUMBER(38, 0)    NOT NULL,
    ACL_ID                      NUMBER(38, 0)    NOT NULL,
    PERMISSION_TYPE_ID          NUMBER(38, 0)    NOT NULL
                                CONSTRAINT CHK_OTPB_PERMISSION_TYPE_ID CHECK (PERMISSION_TYPE_ID IN (1, 3)),
    CONSTRAINT PK_OBJECT_TYPE_PERMISSION_BIND PRIMARY KEY (APP_SID, PRIMARY_OBJECT_TYPE_ID, SECONDARY_OBJECT_TYPE_ID)
)
;



-- 
-- TABLE: DISPOSABLE.OBJECT_TYPE_PERMISSION_TYPE 
--

CREATE TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION_TYPE(
    OBJECT_TYPE_ID        NUMBER(38, 0)    NOT NULL,
    PERMISSION_TYPE_ID    NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK_OBJECT_TYPE_PERMISSION_TYPE PRIMARY KEY (OBJECT_TYPE_ID, PERMISSION_TYPE_ID)
)
;



-- 
-- TABLE: DISPOSABLE.OBJECT_TYPE_RELATIONSHIP 
--

CREATE TABLE DISPOSABLE.OBJECT_TYPE_RELATIONSHIP(
    PRIMARY_OBJECT_TYPE_ID      NUMBER(38, 0)    NOT NULL,
    SECONDARY_OBJECT_TYPE_ID    NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK_OBJECT_TYPE_RELATIONSHIP PRIMARY KEY (PRIMARY_OBJECT_TYPE_ID, SECONDARY_OBJECT_TYPE_ID)
)
;



-- 
-- TABLE: DISPOSABLE.PERMISSION 
--

CREATE TABLE DISPOSABLE.PERMISSION(
    PERMISSION_ID    NUMBER(38, 0)    NOT NULL,
    DESCRIPTION      VARCHAR2(100)    NOT NULL,
    CONSTRAINT PK_PERMISSION PRIMARY KEY (PERMISSION_ID)
)
;



-- 
-- TABLE: DISPOSABLE.PERMISSION_POLICY 
--

CREATE TABLE DISPOSABLE.PERMISSION_POLICY(
    PERMISSION_POLICY_ID    NUMBER(38, 0)    NOT NULL,
    DESCRIPTION             VARCHAR2(100)    NOT NULL,
    CONSTRAINT PK_PERMISSION_POLICY PRIMARY KEY (PERMISSION_POLICY_ID)
)
;



-- 
-- TABLE: DISPOSABLE.PERMISSION_TYPE 
--

CREATE TABLE DISPOSABLE.PERMISSION_TYPE(
    PERMISSION_TYPE_ID    NUMBER(38, 0)    NOT NULL,
    DESCRIPTION           VARCHAR2(100)    NOT NULL,
    CONSTRAINT PK_PERMISSION_TYPE PRIMARY KEY (PERMISSION_TYPE_ID)
)
;



-- 
-- TABLE: DISPOSABLE.ROLE 
--

CREATE TABLE DISPOSABLE.ROLE(
    APP_SID            NUMBER(38, 0)    DEFAULT SYS_CONTEXT('DISPOSABLE', 'APP') NOT NULL,
    ROLE_SID           NUMBER(38, 0)    NOT NULL,
    SYSTEM_ROLE_SID    NUMBER(38, 0),
    CONSTRAINT PK_ROLE PRIMARY KEY (APP_SID, ROLE_SID)
)
;



-- 
-- TABLE: DISPOSABLE.ROLE_MEMBER 
--

CREATE TABLE DISPOSABLE.ROLE_MEMBER(
    APP_SID       NUMBER(38, 0)    DEFAULT SYS_CONTEXT('DISPOSABLE', 'APP') NOT NULL,
    ROLE_SID      NUMBER(38, 0)    NOT NULL,
    OBJECT_SID    NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK_ROLE_MEMBER PRIMARY KEY (APP_SID, ROLE_SID, OBJECT_SID)
)
;



-- 
-- TABLE: DISPOSABLE.SYSTEM_DEVICE 
--

CREATE TABLE DISPOSABLE.SYSTEM_DEVICE(
    DEVICE_SID    NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK_SYSTEM_DEVICE PRIMARY KEY (DEVICE_SID)
)
;



-- 
-- TABLE: DISPOSABLE.SYSTEM_ROLE 
--

CREATE TABLE DISPOSABLE.SYSTEM_ROLE(
    SYSTEM_ROLE_SID    NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK_SYSTEM_ROLE PRIMARY KEY (SYSTEM_ROLE_SID)
)
;



-- 
-- TABLE: DISPOSABLE.SYSTEM_USER 
--

CREATE TABLE DISPOSABLE.SYSTEM_USER(
    USER_SID    NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK_SYSTEM_USER PRIMARY KEY (USER_SID)
)
;



-- 
-- TABLE: DISPOSABLE.SYSTEM_USER_DEVICE 
--

CREATE TABLE DISPOSABLE.SYSTEM_USER_DEVICE(
    USER_SID      NUMBER(38, 0)    NOT NULL,
    DEVICE_SID    NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK_SYSTEM_USER_DEVICE PRIMARY KEY (USER_SID, DEVICE_SID)
)
;



-- 
-- TABLE: DISPOSABLE.USER_DEVICE 
--

CREATE TABLE DISPOSABLE.USER_DEVICE(
    USER_SID      NUMBER(38, 0)    NOT NULL,
    DEVICE_SID    NUMBER(38, 0)    NOT NULL,
    APP_SID       NUMBER(38, 0)    DEFAULT SYS_CONTEXT('DISPOSABLE', 'APP') NOT NULL,
    OBJECT_SID    NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK_USER_DEVICE PRIMARY KEY (USER_SID, DEVICE_SID, APP_SID, OBJECT_SID)
)
;



-- 
-- INDEX: DISPOSABLE.UK_ACL_POSITION 
--

CREATE UNIQUE INDEX DISPOSABLE.UK_ACL_POSITION ON DISPOSABLE.ACE(OBJECT_TYPE_ID, POSITION)
;
-- 
-- TABLE: DISPOSABLE.ACE 
--

ALTER TABLE DISPOSABLE.ACE ADD CONSTRAINT FK_ACE_ACE 
    FOREIGN KEY (APP_SID, INHERITED_FROM_ACL_ID)
    REFERENCES DISPOSABLE.ACE(APP_SID, ACE_ID)
;

ALTER TABLE DISPOSABLE.ACE ADD CONSTRAINT FK_ACL_ACE 
    FOREIGN KEY (APP_SID, ACL_ID, OBJECT_TYPE_ID, PERMISSION_TYPE_ID)
    REFERENCES DISPOSABLE.ACL(APP_SID, ACL_ID, OBJECT_TYPE_ID, PERMISSION_TYPE_ID)
;

ALTER TABLE DISPOSABLE.ACE ADD CONSTRAINT FK_APP_ACE 
    FOREIGN KEY (APP_SID)
    REFERENCES DISPOSABLE.APP(APP_SID)
;

ALTER TABLE DISPOSABLE.ACE ADD CONSTRAINT FK_OBJECT_TYPE_PERMISSION_ACE 
    FOREIGN KEY (OBJECT_TYPE_ID, PERMISSION_ID)
    REFERENCES DISPOSABLE.OBJECT_TYPE_PERMISSION(OBJECT_TYPE_ID, PERMISSION_ID)
;

ALTER TABLE DISPOSABLE.ACE ADD CONSTRAINT FK_PERMISSION_POLICY_ACE 
    FOREIGN KEY (PERMISSION_POLICY_ID)
    REFERENCES DISPOSABLE.PERMISSION_POLICY(PERMISSION_POLICY_ID)
;


-- 
-- TABLE: DISPOSABLE.ACL 
--

ALTER TABLE DISPOSABLE.ACL ADD CONSTRAINT FK_APP_ACL 
    FOREIGN KEY (APP_SID)
    REFERENCES DISPOSABLE.APP(APP_SID)
;

ALTER TABLE DISPOSABLE.ACL ADD CONSTRAINT FK_OTPT_ACL 
    FOREIGN KEY (OBJECT_TYPE_ID, PERMISSION_TYPE_ID)
    REFERENCES DISPOSABLE.OBJECT_TYPE_PERMISSION_TYPE(OBJECT_TYPE_ID, PERMISSION_TYPE_ID)
;


-- 
-- TABLE: DISPOSABLE.APP 
--

ALTER TABLE DISPOSABLE.APP ADD CONSTRAINT FK_OBJECT_APP 
    FOREIGN KEY (APP_SID)
    REFERENCES DISPOSABLE.OBJECT(OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.APP_OBJECT 
--

ALTER TABLE DISPOSABLE.APP_OBJECT ADD CONSTRAINT FK_APP_APP_OBJECT 
    FOREIGN KEY (APP_SID)
    REFERENCES DISPOSABLE.APP(APP_SID)
;

ALTER TABLE DISPOSABLE.APP_OBJECT ADD CONSTRAINT FK_OBJECT_APP_OBJECT 
    FOREIGN KEY (OBJECT_SID)
    REFERENCES DISPOSABLE.OBJECT(OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.APP_USER 
--

ALTER TABLE DISPOSABLE.APP_USER ADD CONSTRAINT FK_AUTH_OBJECT_APP_USER 
    FOREIGN KEY (APP_SID, OBJECT_SID)
    REFERENCES DISPOSABLE.AUTHORIZABLE_OBJECT(APP_SID, OBJECT_SID)
;

ALTER TABLE DISPOSABLE.APP_USER ADD CONSTRAINT FK_SYSTEM_USER_APP_USER 
    FOREIGN KEY (USER_SID)
    REFERENCES DISPOSABLE.SYSTEM_USER(USER_SID)
;


-- 
-- TABLE: DISPOSABLE.AUTHORIZABLE_OBJECT 
--

ALTER TABLE DISPOSABLE.AUTHORIZABLE_OBJECT ADD CONSTRAINT FK_AO_AO 
    FOREIGN KEY (APP_SID, OBJECT_SID)
    REFERENCES DISPOSABLE.APP_OBJECT(APP_SID, OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.OBJECT 
--

ALTER TABLE DISPOSABLE.OBJECT ADD CONSTRAINT FK_OBJECT_OBJECT 
    FOREIGN KEY (PARENT_OBJECT_SID)
    REFERENCES DISPOSABLE.OBJECT(OBJECT_SID)
;

ALTER TABLE DISPOSABLE.OBJECT ADD CONSTRAINT FK_OBJECT_OBJECT_TYPE_OBJECT 
    FOREIGN KEY (OBJECT_TYPE_ID, OBJECT_SID)
    REFERENCES DISPOSABLE.OBJECT_OBJECT_TYPE(OBJECT_TYPE_ID, OBJECT_SID)
;

ALTER TABLE DISPOSABLE.OBJECT ADD CONSTRAINT FK_OBJECT_POOL_OBJECT 
    FOREIGN KEY (OBJECT_SID)
    REFERENCES DISPOSABLE.OBJECT_POOL(OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.OBJECT_OBJECT_TYPE 
--

ALTER TABLE DISPOSABLE.OBJECT_OBJECT_TYPE ADD CONSTRAINT FK_OBJECT_POOL_OOT 
    FOREIGN KEY (OBJECT_SID)
    REFERENCES DISPOSABLE.OBJECT_POOL(OBJECT_SID)
;

ALTER TABLE DISPOSABLE.OBJECT_OBJECT_TYPE ADD CONSTRAINT FK_OBJECT_TYPE_OOT 
    FOREIGN KEY (OBJECT_TYPE_ID)
    REFERENCES DISPOSABLE.OBJECT_TYPE(OBJECT_TYPE_ID)
;


-- 
-- TABLE: DISPOSABLE.OBJECT_PERMISSION_BINDER 
--

ALTER TABLE DISPOSABLE.OBJECT_PERMISSION_BINDER ADD CONSTRAINT FK_ACL_OPB 
    FOREIGN KEY (APP_SID, ACL_ID, SECONDARY_OBJECT_TYPE_ID, PERMISSION_TYPE_ID)
    REFERENCES DISPOSABLE.ACL(APP_SID, ACL_ID, OBJECT_TYPE_ID, PERMISSION_TYPE_ID)
;

ALTER TABLE DISPOSABLE.OBJECT_PERMISSION_BINDER ADD CONSTRAINT FK_OOT_OPB_1 
    FOREIGN KEY (PRIMARY_OBJECT_TYPE_ID, PRIMARY_OBJECT_SID)
    REFERENCES DISPOSABLE.OBJECT_OBJECT_TYPE(OBJECT_TYPE_ID, OBJECT_SID)
;

ALTER TABLE DISPOSABLE.OBJECT_PERMISSION_BINDER ADD CONSTRAINT FK_OOT_OPB_2 
    FOREIGN KEY (SECONDARY_OBJECT_TYPE_ID, SECONDARY_OBJECT_SID)
    REFERENCES DISPOSABLE.OBJECT_OBJECT_TYPE(OBJECT_TYPE_ID, OBJECT_SID)
;

ALTER TABLE DISPOSABLE.OBJECT_PERMISSION_BINDER ADD CONSTRAINT FK_OR_OPB 
    FOREIGN KEY (PRIMARY_OBJECT_SID, SECONDARY_OBJECT_SID, APP_SID)
    REFERENCES DISPOSABLE.OBJECT_RELATIONSHIP(APP_SID, SECONDARY_OBJECT_SID, PRIMARY_OBJECT_SID)
;

ALTER TABLE DISPOSABLE.OBJECT_PERMISSION_BINDER ADD CONSTRAINT FK_OTR_OPB 
    FOREIGN KEY (PRIMARY_OBJECT_TYPE_ID, SECONDARY_OBJECT_TYPE_ID)
    REFERENCES DISPOSABLE.OBJECT_TYPE_RELATIONSHIP(PRIMARY_OBJECT_TYPE_ID, SECONDARY_OBJECT_TYPE_ID)
;


-- 
-- TABLE: DISPOSABLE.OBJECT_RELATIONSHIP 
--

ALTER TABLE DISPOSABLE.OBJECT_RELATIONSHIP ADD CONSTRAINT FK_APP_OBJECT_OR 
    FOREIGN KEY (APP_SID, SECONDARY_OBJECT_SID)
    REFERENCES DISPOSABLE.APP_OBJECT(APP_SID, OBJECT_SID)
;

ALTER TABLE DISPOSABLE.OBJECT_RELATIONSHIP ADD CONSTRAINT FK_AUTH_OBJECT_OR 
    FOREIGN KEY (APP_SID, PRIMARY_OBJECT_SID)
    REFERENCES DISPOSABLE.AUTHORIZABLE_OBJECT(APP_SID, OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.OBJECT_TYPE_PERMISSION 
--

ALTER TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION ADD CONSTRAINT FK_OBJECT_TYPE_OTP 
    FOREIGN KEY (OBJECT_TYPE_ID)
    REFERENCES DISPOSABLE.OBJECT_TYPE(OBJECT_TYPE_ID)
;

ALTER TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION ADD CONSTRAINT FK_PERMISSION_OTP 
    FOREIGN KEY (PERMISSION_ID)
    REFERENCES DISPOSABLE.PERMISSION(PERMISSION_ID)
;


-- 
-- TABLE: DISPOSABLE.OBJECT_TYPE_PERMISSION_BINDER 
--

ALTER TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION_BINDER ADD CONSTRAINT FK_ACL_OTPB 
    FOREIGN KEY (APP_SID, ACL_ID, SECONDARY_OBJECT_TYPE_ID, PERMISSION_TYPE_ID)
    REFERENCES DISPOSABLE.ACL(APP_SID, ACL_ID, OBJECT_TYPE_ID, PERMISSION_TYPE_ID)
;

ALTER TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION_BINDER ADD CONSTRAINT FK_APP_OTPB 
    FOREIGN KEY (APP_SID)
    REFERENCES DISPOSABLE.APP(APP_SID)
;

ALTER TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION_BINDER ADD CONSTRAINT FK_OTR_OTPB 
    FOREIGN KEY (PRIMARY_OBJECT_TYPE_ID, SECONDARY_OBJECT_TYPE_ID)
    REFERENCES DISPOSABLE.OBJECT_TYPE_RELATIONSHIP(PRIMARY_OBJECT_TYPE_ID, SECONDARY_OBJECT_TYPE_ID)
;


-- 
-- TABLE: DISPOSABLE.OBJECT_TYPE_PERMISSION_TYPE 
--

ALTER TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION_TYPE ADD CONSTRAINT FK_OBJECT_TYPE_OTPT 
    FOREIGN KEY (OBJECT_TYPE_ID)
    REFERENCES DISPOSABLE.OBJECT_TYPE(OBJECT_TYPE_ID)
;

ALTER TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION_TYPE ADD CONSTRAINT FK_PROGRESSION_TYPE_OTPT 
    FOREIGN KEY (PERMISSION_TYPE_ID)
    REFERENCES DISPOSABLE.PERMISSION_TYPE(PERMISSION_TYPE_ID)
;


-- 
-- TABLE: DISPOSABLE.OBJECT_TYPE_RELATIONSHIP 
--

ALTER TABLE DISPOSABLE.OBJECT_TYPE_RELATIONSHIP ADD CONSTRAINT FK_OBJECT_TYPE_OTR_1 
    FOREIGN KEY (PRIMARY_OBJECT_TYPE_ID)
    REFERENCES DISPOSABLE.OBJECT_TYPE(OBJECT_TYPE_ID)
;

ALTER TABLE DISPOSABLE.OBJECT_TYPE_RELATIONSHIP ADD CONSTRAINT FK_OBJECT_TYPE_OTR_2 
    FOREIGN KEY (SECONDARY_OBJECT_TYPE_ID)
    REFERENCES DISPOSABLE.OBJECT_TYPE(OBJECT_TYPE_ID)
;


-- 
-- TABLE: DISPOSABLE.ROLE 
--

ALTER TABLE DISPOSABLE.ROLE ADD CONSTRAINT FK_AUTHORIZABLE_OBJECT_ROLE 
    FOREIGN KEY (APP_SID, ROLE_SID)
    REFERENCES DISPOSABLE.AUTHORIZABLE_OBJECT(APP_SID, OBJECT_SID)
;

ALTER TABLE DISPOSABLE.ROLE ADD CONSTRAINT FK_SYSTEM_ROLE_ROLE 
    FOREIGN KEY (SYSTEM_ROLE_SID)
    REFERENCES DISPOSABLE.SYSTEM_ROLE(SYSTEM_ROLE_SID)
;


-- 
-- TABLE: DISPOSABLE.ROLE_MEMBER 
--

ALTER TABLE DISPOSABLE.ROLE_MEMBER ADD CONSTRAINT FK_AO_ROLE_MEMBER 
    FOREIGN KEY (APP_SID, OBJECT_SID)
    REFERENCES DISPOSABLE.AUTHORIZABLE_OBJECT(APP_SID, OBJECT_SID)
;

ALTER TABLE DISPOSABLE.ROLE_MEMBER ADD CONSTRAINT FK_ROLE_ROLE_MEMBER 
    FOREIGN KEY (APP_SID, OBJECT_SID)
    REFERENCES DISPOSABLE.ROLE(APP_SID, ROLE_SID)
;


-- 
-- TABLE: DISPOSABLE.SYSTEM_DEVICE 
--

ALTER TABLE DISPOSABLE.SYSTEM_DEVICE ADD CONSTRAINT FK_OBJECT_SYSTEM_DEVICE 
    FOREIGN KEY (DEVICE_SID)
    REFERENCES DISPOSABLE.OBJECT(OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.SYSTEM_ROLE 
--

ALTER TABLE DISPOSABLE.SYSTEM_ROLE ADD CONSTRAINT FK_OBJECT_SYSTEM_ROLE 
    FOREIGN KEY (SYSTEM_ROLE_SID)
    REFERENCES DISPOSABLE.OBJECT(OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.SYSTEM_USER 
--

ALTER TABLE DISPOSABLE.SYSTEM_USER ADD CONSTRAINT FK_OBJECT_SYSTEM_USER 
    FOREIGN KEY (USER_SID)
    REFERENCES DISPOSABLE.OBJECT(OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.SYSTEM_USER_DEVICE 
--

ALTER TABLE DISPOSABLE.SYSTEM_USER_DEVICE ADD CONSTRAINT FK_SYSTEM_DEVICE_SUD 
    FOREIGN KEY (DEVICE_SID)
    REFERENCES DISPOSABLE.SYSTEM_DEVICE(DEVICE_SID)
;

ALTER TABLE DISPOSABLE.SYSTEM_USER_DEVICE ADD CONSTRAINT FK_SYSTEM_USER_SUD 
    FOREIGN KEY (USER_SID)
    REFERENCES DISPOSABLE.SYSTEM_USER(USER_SID)
;


-- 
-- TABLE: DISPOSABLE.USER_DEVICE 
--

ALTER TABLE DISPOSABLE.USER_DEVICE ADD CONSTRAINT FK_APP_USER_USER_DEVICE 
    FOREIGN KEY (USER_SID, APP_SID, OBJECT_SID)
    REFERENCES DISPOSABLE.APP_USER(USER_SID, APP_SID, OBJECT_SID)
;

ALTER TABLE DISPOSABLE.USER_DEVICE ADD CONSTRAINT FK_SUD_USER_DEVICE 
    FOREIGN KEY (USER_SID, DEVICE_SID)
    REFERENCES DISPOSABLE.SYSTEM_USER_DEVICE(USER_SID, DEVICE_SID)
;


