--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      c
-- Project :      disposable.dm1
-- Author :       Casey
--
-- Date Created : Wednesday, November 06, 2013 21:36:57
-- Target DBMS : MySQL 5.x
--

-- 
-- TABLE: DISPOSABLE.ACE 
--

CREATE TABLE DISPOSABLE.ACE(
    APP_SID                  INT UNSIGNED  NOT NULL,
    ACE_ID                   INT UNSIGNED  NOT NULL,
    ACL_ID                   INT UNSIGNED  NOT NULL,
    OBJECT_TYPE_ID           INT UNSIGNED  NOT NULL,
    PERMISSION_TYPE_ID       INT UNSIGNED  NOT NULL,
    PERMISSION_POLICY_ID     INT UNSIGNED  NOT NULL,
    PERMISSION_ID            INT UNSIGNED  NOT NULL,
    POSITION                 INT UNSIGNED  NOT NULL,
    INHERITED_FROM_ACL_ID    INT UNSIGNED,
    INHERITABLE              INT UNSIGNED  NOT NULL,
    INHERIT_INHERITABLE      INT UNSIGNED  NOT NULL,
    CONSTRAINT CHK_ACE_INHERITABLE CHECK (INHERITABLE IN (0, 1)),
    CONSTRAINT CHK_ACE_INHERIT_INHERITABLE CHECK (INHERIT_INHERITABLE IN (0, 1)),
    PRIMARY KEY (APP_SID, ACE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.ACE_ID_POOL 
--

CREATE TABLE DISPOSABLE.ACE_ID_POOL(
    ACE_ID    INT UNSIGNED  AUTO_INCREMENT,
    PRIMARY KEY (ACE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.ACL 
--

CREATE TABLE DISPOSABLE.ACL(
    APP_SID               INT UNSIGNED  NOT NULL,
    ACL_ID                INT    NOT NULL,
    OBJECT_TYPE_ID        INT UNSIGNED  NOT NULL,
    PERMISSION_TYPE_ID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (APP_SID, ACL_ID, OBJECT_TYPE_ID, PERMISSION_TYPE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.ACL_ID_POOL 
--

CREATE TABLE DISPOSABLE.ACL_ID_POOL(
    ACL_ID    INT UNSIGNED  AUTO_INCREMENT,
    PRIMARY KEY (ACL_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.APP 
--

CREATE TABLE DISPOSABLE.APP(
    APP_SID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (APP_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.APP_OBJECT 
--

CREATE TABLE DISPOSABLE.APP_OBJECT(
    APP_SID       INT UNSIGNED  NOT NULL,
    OBJECT_SID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (APP_SID, OBJECT_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.AUTHORIZABLE_OBJECT 
--

CREATE TABLE DISPOSABLE.AUTHORIZABLE_OBJECT(
    APP_SID       INT UNSIGNED  NOT NULL,
    OBJECT_SID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (APP_SID, OBJECT_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.CONSTANT 
--

CREATE TABLE DISPOSABLE.CONSTANT(
    SECTION    VARCHAR(100)    NOT NULL,
    NAME       VARCHAR(100)    NOT NULL,
    ID         INT UNSIGNED    NOT NULL,
    CONSTRAINT CHK_CONSTANT_SECTION CHECK (SECTION = UPPER(SECTION)),
    CONSTRAINT CHK_CONSTANT_NAME CHECK (NAME = UPPER(NAME)),
    PRIMARY KEY (SECTION, NAME)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.OBJECT 
--

CREATE TABLE DISPOSABLE.OBJECT(
    OBJECT_SID           INT UNSIGNED  NOT NULL,
    OBJECT_TYPE_ID       INT UNSIGNED  NOT NULL,
    PARENT_OBJECT_SID    INT UNSIGNED,
    PRIMARY KEY (OBJECT_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.OBJECT_OBJECT_TYPE 
--

CREATE TABLE DISPOSABLE.OBJECT_OBJECT_TYPE(
    OBJECT_TYPE_ID    INT UNSIGNED  NOT NULL,
    OBJECT_SID        INT UNSIGNED  NOT NULL,
    PRIMARY KEY (OBJECT_TYPE_ID, OBJECT_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.OBJECT_PERMISSION_BINDER 
--

CREATE TABLE DISPOSABLE.OBJECT_PERMISSION_BINDER(
    APP_SID                     INT UNSIGNED  NOT NULL,
    PRIMARY_OBJECT_TYPE_ID      INT UNSIGNED  NOT NULL,
    PRIMARY_OBJECT_SID          INT UNSIGNED  NOT NULL,
    SECONDARY_OBJECT_TYPE_ID    INT UNSIGNED  NOT NULL,
    SECONDARY_OBJECT_SID        INT UNSIGNED  NOT NULL,
    ACL_ID                      INT UNSIGNED  NOT NULL,
    PERMISSION_TYPE_ID          INT UNSIGNED  NOT NULL,
    CONSTRAINT CHK_OBJECT_PERMISSION_BINDER_PERMISSION_TYPE_ID CHECK (PERMISSION_TYPE_ID IN (2, 3)),
    PRIMARY KEY (APP_SID, PRIMARY_OBJECT_TYPE_ID, PRIMARY_OBJECT_SID, SECONDARY_OBJECT_TYPE_ID, SECONDARY_OBJECT_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.OBJECT_RELATIONSHIP 
--

CREATE TABLE DISPOSABLE.OBJECT_RELATIONSHIP(
    APP_SID                 INT UNSIGNED  NOT NULL,
    PRIMARY_OBJECT_SID      INT UNSIGNED  NOT NULL,
    SECONDARY_OBJECT_SID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (APP_SID, PRIMARY_OBJECT_SID, SECONDARY_OBJECT_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.OBJECT_SID_POOL 
--

CREATE TABLE DISPOSABLE.OBJECT_SID_POOL(
    OBJECT_SID    INT UNSIGNED  AUTO_INCREMENT,
    PRIMARY KEY (OBJECT_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.OBJECT_TYPE 
--

CREATE TABLE DISPOSABLE.OBJECT_TYPE(
    OBJECT_TYPE_ID    INT UNSIGNED    NOT NULL,
    DESCRIPTION       VARCHAR(100)    NOT NULL,
    PRIMARY KEY (OBJECT_TYPE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.OBJECT_TYPE_PERMISSION 
--

CREATE TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION(
    OBJECT_TYPE_ID    INT UNSIGNED  NOT NULL,
    PERMISSION_ID     INT UNSIGNED  NOT NULL,
    PRIMARY KEY (OBJECT_TYPE_ID, PERMISSION_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.OBJECT_TYPE_PERMISSION_BINDER 
--

CREATE TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION_BINDER(
    APP_SID                     INT UNSIGNED  NOT NULL,
    PRIMARY_OBJECT_TYPE_ID      INT UNSIGNED  NOT NULL,
    SECONDARY_OBJECT_TYPE_ID    INT UNSIGNED  NOT NULL,
    ACL_ID                      INT UNSIGNED  NOT NULL,
    PERMISSION_TYPE_ID          INT UNSIGNED  NOT NULL,
    CONSTRAINT CHK_OBJECT_TYPE_PERMISSION_BINDER_PERMISSION_TYPE_ID CHECK (PERMISSION_TYPE_ID IN (1, 3)),
    PRIMARY KEY (APP_SID, PRIMARY_OBJECT_TYPE_ID, SECONDARY_OBJECT_TYPE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.OBJECT_TYPE_PERMISSION_TYPE 
--

CREATE TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION_TYPE(
    OBJECT_TYPE_ID        INT UNSIGNED  NOT NULL,
    PERMISSION_TYPE_ID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (OBJECT_TYPE_ID, PERMISSION_TYPE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.OBJECT_TYPE_RELATIONSHIP 
--

CREATE TABLE DISPOSABLE.OBJECT_TYPE_RELATIONSHIP(
    PRIMARY_OBJECT_TYPE_ID      INT UNSIGNED  NOT NULL,
    SECONDARY_OBJECT_TYPE_ID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (PRIMARY_OBJECT_TYPE_ID, SECONDARY_OBJECT_TYPE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.PERMISSION 
--

CREATE TABLE DISPOSABLE.PERMISSION(
    PERMISSION_ID    INT UNSIGNED    NOT NULL,
    DESCRIPTION      VARCHAR(100)    NOT NULL,
    PRIMARY KEY (PERMISSION_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.PERMISSION_POLICY 
--

CREATE TABLE DISPOSABLE.PERMISSION_POLICY(
    PERMISSION_POLICY_ID    INT UNSIGNED    NOT NULL,
    DESCRIPTION             VARCHAR(100)    NOT NULL,
    PRIMARY KEY (PERMISSION_POLICY_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.PERMISSION_TYPE 
--

CREATE TABLE DISPOSABLE.PERMISSION_TYPE(
    PERMISSION_TYPE_ID    INT UNSIGNED    NOT NULL,
    DESCRIPTION           VARCHAR(100)    NOT NULL,
    PRIMARY KEY (PERMISSION_TYPE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.ROLE 
--

CREATE TABLE DISPOSABLE.ROLE(
    APP_SID     INT UNSIGNED  NOT NULL,
    ROLE_SID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (APP_SID, ROLE_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.ROLE_MEMBER 
--

CREATE TABLE DISPOSABLE.ROLE_MEMBER(
    APP_SID       INT UNSIGNED  NOT NULL,
    ROLE_SID      INT UNSIGNED  NOT NULL,
    MEMBER_SID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (APP_SID, ROLE_SID, MEMBER_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.SYSTEM_DEVICE 
--

CREATE TABLE DISPOSABLE.SYSTEM_DEVICE(
    DEVICE_SID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (DEVICE_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.SYSTEM_ROLE 
--

CREATE TABLE DISPOSABLE.SYSTEM_ROLE(
    SYSTEM_ROLE_SID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (SYSTEM_ROLE_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.SYSTEM_USER 
--

CREATE TABLE DISPOSABLE.SYSTEM_USER(
    USER_SID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (USER_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.SYSTEM_USER_DEVICE 
--

CREATE TABLE DISPOSABLE.SYSTEM_USER_DEVICE(
    USER_SID      INT UNSIGNED  NOT NULL,
    DEVICE_SID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (USER_SID, DEVICE_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.USER 
--

CREATE TABLE DISPOSABLE.USER(
    APP_SID     INT UNSIGNED  NOT NULL,
    USER_SID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (APP_SID, USER_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.USER_DEVICE 
--

CREATE TABLE DISPOSABLE.USER_DEVICE(
    APP_SID       INT UNSIGNED  NOT NULL,
    USER_SID      INT UNSIGNED  NOT NULL,
    DEVICE_SID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (APP_SID, USER_SID, DEVICE_SID)
)ENGINE=INNODB
;



-- 
-- INDEX: UK_ACL_POSITION 
--

CREATE UNIQUE INDEX UK_ACL_POSITION ON DISPOSABLE.ACE(ACL_ID, OBJECT_TYPE_ID, POSITION)
;
-- 
-- TABLE: DISPOSABLE.ACE 
--

ALTER TABLE DISPOSABLE.ACE ADD CONSTRAINT FK_ACE_ACE 
    FOREIGN KEY (APP_SID, INHERITED_FROM_ACL_ID)
    REFERENCES DISPOSABLE.ACE(APP_SID, ACE_ID)
;

ALTER TABLE DISPOSABLE.ACE ADD CONSTRAINT FK_ACE_ID_POOL_ACE 
    FOREIGN KEY (ACE_ID)
    REFERENCES DISPOSABLE.ACE_ID_POOL(ACE_ID)
;

ALTER TABLE DISPOSABLE.ACE ADD CONSTRAINT FK_ACL_ACE 
    FOREIGN KEY (APP_SID, ACL_ID, OBJECT_TYPE_ID, PERMISSION_TYPE_ID)
    REFERENCES DISPOSABLE.ACL(APP_SID, ACL_ID, OBJECT_TYPE_ID, PERMISSION_TYPE_ID)
;

ALTER TABLE DISPOSABLE.ACE ADD CONSTRAINT FK_APP_ACE 
    FOREIGN KEY (APP_SID)
    REFERENCES DISPOSABLE.APP(APP_SID)
;

ALTER TABLE DISPOSABLE.ACE ADD CONSTRAINT FK_OBJECT_TYPE_PERMISSION_ACE 
    FOREIGN KEY (OBJECT_TYPE_ID, PERMISSION_ID)
    REFERENCES DISPOSABLE.OBJECT_TYPE_PERMISSION(OBJECT_TYPE_ID, PERMISSION_ID)
;

ALTER TABLE DISPOSABLE.ACE ADD CONSTRAINT FK_PERMISSION_POLICY_ACE 
    FOREIGN KEY (PERMISSION_POLICY_ID)
    REFERENCES DISPOSABLE.PERMISSION_POLICY(PERMISSION_POLICY_ID)
;


-- 
-- TABLE: DISPOSABLE.ACL 
--

ALTER TABLE DISPOSABLE.ACL ADD CONSTRAINT FK_ACL_ID_POOL_ACL 
    FOREIGN KEY (ACL_ID)
    REFERENCES DISPOSABLE.ACL_ID_POOL(ACL_ID)
;

ALTER TABLE DISPOSABLE.ACL ADD CONSTRAINT FK_APP_ACL 
    FOREIGN KEY (APP_SID)
    REFERENCES DISPOSABLE.APP(APP_SID)
;

ALTER TABLE DISPOSABLE.ACL ADD CONSTRAINT FK_OBJECT_TYPE_PERMISSION_TYPE_ACL 
    FOREIGN KEY (OBJECT_TYPE_ID, PERMISSION_TYPE_ID)
    REFERENCES DISPOSABLE.OBJECT_TYPE_PERMISSION_TYPE(OBJECT_TYPE_ID, PERMISSION_TYPE_ID)
;


-- 
-- TABLE: DISPOSABLE.APP 
--

ALTER TABLE DISPOSABLE.APP ADD CONSTRAINT FK_OBJECT_APP 
    FOREIGN KEY (APP_SID)
    REFERENCES DISPOSABLE.OBJECT(OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.APP_OBJECT 
--

ALTER TABLE DISPOSABLE.APP_OBJECT ADD CONSTRAINT FK_APP_APP_OBJECT 
    FOREIGN KEY (APP_SID)
    REFERENCES DISPOSABLE.APP(APP_SID)
;

ALTER TABLE DISPOSABLE.APP_OBJECT ADD CONSTRAINT FK_OBJECT_APP_OBJECT 
    FOREIGN KEY (OBJECT_SID)
    REFERENCES DISPOSABLE.OBJECT(OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.AUTHORIZABLE_OBJECT 
--

ALTER TABLE DISPOSABLE.AUTHORIZABLE_OBJECT ADD CONSTRAINT FK_APP_OBJECT_AUTHORIZABLE_OBJECT 
    FOREIGN KEY (APP_SID, OBJECT_SID)
    REFERENCES DISPOSABLE.APP_OBJECT(APP_SID, OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.OBJECT 
--

ALTER TABLE DISPOSABLE.OBJECT ADD CONSTRAINT FK_OBJECT_OBJECT 
    FOREIGN KEY (PARENT_OBJECT_SID)
    REFERENCES DISPOSABLE.OBJECT(OBJECT_SID)
;

ALTER TABLE DISPOSABLE.OBJECT ADD CONSTRAINT FK_OBJECT_OBJECT_TYPE_OBJECT 
    FOREIGN KEY (OBJECT_SID, OBJECT_TYPE_ID)
    REFERENCES DISPOSABLE.OBJECT_OBJECT_TYPE(OBJECT_TYPE_ID, OBJECT_SID)
;

ALTER TABLE DISPOSABLE.OBJECT ADD CONSTRAINT FK_OBJECT_SID_POOL_OBJECT 
    FOREIGN KEY (OBJECT_SID)
    REFERENCES DISPOSABLE.OBJECT_SID_POOL(OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.OBJECT_OBJECT_TYPE 
--

ALTER TABLE DISPOSABLE.OBJECT_OBJECT_TYPE ADD CONSTRAINT FK_OBJECT_SID_POOL_OBJECT_OBJECT_TYPE 
    FOREIGN KEY (OBJECT_SID)
    REFERENCES DISPOSABLE.OBJECT_SID_POOL(OBJECT_SID)
;

ALTER TABLE DISPOSABLE.OBJECT_OBJECT_TYPE ADD CONSTRAINT FK_OBJECT_TYPE_OBJECT_OBJECT_TYPE 
    FOREIGN KEY (OBJECT_TYPE_ID)
    REFERENCES DISPOSABLE.OBJECT_TYPE(OBJECT_TYPE_ID)
;


-- 
-- TABLE: DISPOSABLE.OBJECT_PERMISSION_BINDER 
--

ALTER TABLE DISPOSABLE.OBJECT_PERMISSION_BINDER ADD CONSTRAINT FK_ACL_OBJECT_PERMISSION_BINDER 
    FOREIGN KEY (APP_SID, SECONDARY_OBJECT_TYPE_ID, ACL_ID, PERMISSION_TYPE_ID)
    REFERENCES DISPOSABLE.ACL(APP_SID, ACL_ID, OBJECT_TYPE_ID, PERMISSION_TYPE_ID)
;

ALTER TABLE DISPOSABLE.OBJECT_PERMISSION_BINDER ADD CONSTRAINT FK_OBJECT_OBJECT_TYPE_OBJECT_PERMISSION_BINDER_1 
    FOREIGN KEY (PRIMARY_OBJECT_TYPE_ID, PRIMARY_OBJECT_SID)
    REFERENCES DISPOSABLE.OBJECT_OBJECT_TYPE(OBJECT_TYPE_ID, OBJECT_SID)
;

ALTER TABLE DISPOSABLE.OBJECT_PERMISSION_BINDER ADD CONSTRAINT FK_OBJECT_OBJECT_TYPE_OBJECT_PERMISSION_BINDER_2 
    FOREIGN KEY (SECONDARY_OBJECT_TYPE_ID, SECONDARY_OBJECT_SID)
    REFERENCES DISPOSABLE.OBJECT_OBJECT_TYPE(OBJECT_TYPE_ID, OBJECT_SID)
;

ALTER TABLE DISPOSABLE.OBJECT_PERMISSION_BINDER ADD CONSTRAINT FK_OBJECT_RELATIONSHIP_OBJECT_PERMISSION_BINDER 
    FOREIGN KEY (APP_SID, PRIMARY_OBJECT_SID, SECONDARY_OBJECT_SID)
    REFERENCES DISPOSABLE.OBJECT_RELATIONSHIP(APP_SID, PRIMARY_OBJECT_SID, SECONDARY_OBJECT_SID)
;

ALTER TABLE DISPOSABLE.OBJECT_PERMISSION_BINDER ADD CONSTRAINT FK_OBJECT_TYPE_RELATIONSHIP_OBJECT_PERMISSION_BINDER 
    FOREIGN KEY (PRIMARY_OBJECT_TYPE_ID, SECONDARY_OBJECT_TYPE_ID)
    REFERENCES DISPOSABLE.OBJECT_TYPE_RELATIONSHIP(PRIMARY_OBJECT_TYPE_ID, SECONDARY_OBJECT_TYPE_ID)
;


-- 
-- TABLE: DISPOSABLE.OBJECT_RELATIONSHIP 
--

ALTER TABLE DISPOSABLE.OBJECT_RELATIONSHIP ADD CONSTRAINT FK_APP_OBJECT_OBJECT_RELATIONSHIP 
    FOREIGN KEY (APP_SID, SECONDARY_OBJECT_SID)
    REFERENCES DISPOSABLE.APP_OBJECT(APP_SID, OBJECT_SID)
;

ALTER TABLE DISPOSABLE.OBJECT_RELATIONSHIP ADD CONSTRAINT FK_AUTHORIZABLE_OBJECT_OBJECT_RELATIONSHIP 
    FOREIGN KEY (APP_SID, PRIMARY_OBJECT_SID)
    REFERENCES DISPOSABLE.AUTHORIZABLE_OBJECT(APP_SID, OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.OBJECT_TYPE_PERMISSION 
--

ALTER TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION ADD CONSTRAINT FK_OBJECT_TYPE_OBJECT_TYPE_PERMISSION 
    FOREIGN KEY (OBJECT_TYPE_ID)
    REFERENCES DISPOSABLE.OBJECT_TYPE(OBJECT_TYPE_ID)
;

ALTER TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION ADD CONSTRAINT FK_PERMISSION_OBJECT_TYPE_PERMISSION 
    FOREIGN KEY (PERMISSION_ID)
    REFERENCES DISPOSABLE.PERMISSION(PERMISSION_ID)
;


-- 
-- TABLE: DISPOSABLE.OBJECT_TYPE_PERMISSION_BINDER 
--

ALTER TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION_BINDER ADD CONSTRAINT FK_ACL_OBJECT_TYPE_PERMISSION_BINDER 
    FOREIGN KEY (APP_SID, SECONDARY_OBJECT_TYPE_ID, ACL_ID, PERMISSION_TYPE_ID)
    REFERENCES DISPOSABLE.ACL(APP_SID, ACL_ID, OBJECT_TYPE_ID, PERMISSION_TYPE_ID)
;

ALTER TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION_BINDER ADD CONSTRAINT FK_APP_OBJECT_TYPE_PERMISSION_BINDER 
    FOREIGN KEY (APP_SID)
    REFERENCES DISPOSABLE.APP(APP_SID)
;

ALTER TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION_BINDER ADD CONSTRAINT FK_OBJECT_TYPE_RELATIONSHIP_OBJECT_TYPE_PERMISSION_BINDER 
    FOREIGN KEY (PRIMARY_OBJECT_TYPE_ID, SECONDARY_OBJECT_TYPE_ID)
    REFERENCES DISPOSABLE.OBJECT_TYPE_RELATIONSHIP(PRIMARY_OBJECT_TYPE_ID, SECONDARY_OBJECT_TYPE_ID)
;


-- 
-- TABLE: DISPOSABLE.OBJECT_TYPE_PERMISSION_TYPE 
--

ALTER TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION_TYPE ADD CONSTRAINT FK_OBJECT_TYPE_OBJECT_TYPE_PERMISSION_TYPE 
    FOREIGN KEY (OBJECT_TYPE_ID)
    REFERENCES DISPOSABLE.OBJECT_TYPE(OBJECT_TYPE_ID)
;

ALTER TABLE DISPOSABLE.OBJECT_TYPE_PERMISSION_TYPE ADD CONSTRAINT FK_PERMISSION_TYPE_OBJECT_TYPE_PERMISSION_TYPE 
    FOREIGN KEY (PERMISSION_TYPE_ID)
    REFERENCES DISPOSABLE.PERMISSION_TYPE(PERMISSION_TYPE_ID)
;


-- 
-- TABLE: DISPOSABLE.OBJECT_TYPE_RELATIONSHIP 
--

ALTER TABLE DISPOSABLE.OBJECT_TYPE_RELATIONSHIP ADD CONSTRAINT FK_OBJECT_TYPE_OBJECT_TYPE_RELATIONSHIP_1 
    FOREIGN KEY (PRIMARY_OBJECT_TYPE_ID)
    REFERENCES DISPOSABLE.OBJECT_TYPE(OBJECT_TYPE_ID)
;

ALTER TABLE DISPOSABLE.OBJECT_TYPE_RELATIONSHIP ADD CONSTRAINT FK_OBJECT_TYPE_OBJECT_TYPE_RELATIONSHIP_2 
    FOREIGN KEY (SECONDARY_OBJECT_TYPE_ID)
    REFERENCES DISPOSABLE.OBJECT_TYPE(OBJECT_TYPE_ID)
;


-- 
-- TABLE: DISPOSABLE.ROLE 
--

ALTER TABLE DISPOSABLE.ROLE ADD CONSTRAINT FK_AUTHORIZABLE_OBJECT_ROLE 
    FOREIGN KEY (APP_SID, ROLE_SID)
    REFERENCES DISPOSABLE.AUTHORIZABLE_OBJECT(APP_SID, OBJECT_SID)
;

-- 
-- TABLE: DISPOSABLE.ROLE_MEMBER 
--

ALTER TABLE DISPOSABLE.ROLE_MEMBER ADD CONSTRAINT FK_AUTHORIZABLE_OBJECT_ROLE_MEMBER 
    FOREIGN KEY (APP_SID, MEMBER_SID)
    REFERENCES DISPOSABLE.AUTHORIZABLE_OBJECT(APP_SID, OBJECT_SID)
;

ALTER TABLE DISPOSABLE.ROLE_MEMBER ADD CONSTRAINT FK_ROLE_ROLE_MEMBER 
    FOREIGN KEY (APP_SID, ROLE_SID)
    REFERENCES DISPOSABLE.ROLE(APP_SID, ROLE_SID)
;


-- 
-- TABLE: DISPOSABLE.SYSTEM_DEVICE 
--

ALTER TABLE DISPOSABLE.SYSTEM_DEVICE ADD CONSTRAINT FK_OBJECT_SYSTEM_DEVICE 
    FOREIGN KEY (DEVICE_SID)
    REFERENCES DISPOSABLE.OBJECT(OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.SYSTEM_ROLE 
--

ALTER TABLE DISPOSABLE.SYSTEM_ROLE ADD CONSTRAINT FK_OBJECT_SYSTEM_ROLE 
    FOREIGN KEY (SYSTEM_ROLE_SID)
    REFERENCES DISPOSABLE.OBJECT(OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.SYSTEM_USER 
--

ALTER TABLE DISPOSABLE.SYSTEM_USER ADD CONSTRAINT FK_OBJECT_SYSTEM_USER 
    FOREIGN KEY (USER_SID)
    REFERENCES DISPOSABLE.OBJECT(OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.SYSTEM_USER_DEVICE 
--

ALTER TABLE DISPOSABLE.SYSTEM_USER_DEVICE ADD CONSTRAINT FK_SYSTEM_DEVICE_SYSTEM_USER_DEVICE 
    FOREIGN KEY (DEVICE_SID)
    REFERENCES DISPOSABLE.SYSTEM_DEVICE(DEVICE_SID)
;

ALTER TABLE DISPOSABLE.SYSTEM_USER_DEVICE ADD CONSTRAINT FK_SYSTEM_USER_SYSTEM_USER_DEVICE 
    FOREIGN KEY (USER_SID)
    REFERENCES DISPOSABLE.SYSTEM_USER(USER_SID)
;


-- 
-- TABLE: DISPOSABLE.USER 
--

ALTER TABLE DISPOSABLE.USER ADD CONSTRAINT FK_AUTHORIZABLE_OBJECT_USER 
    FOREIGN KEY (APP_SID, USER_SID)
    REFERENCES DISPOSABLE.AUTHORIZABLE_OBJECT(APP_SID, OBJECT_SID)
;

ALTER TABLE DISPOSABLE.USER ADD CONSTRAINT FK_SYSTEM_USER_USER 
    FOREIGN KEY (USER_SID)
    REFERENCES DISPOSABLE.SYSTEM_USER(USER_SID)
;


-- 
-- TABLE: DISPOSABLE.USER_DEVICE 
--

ALTER TABLE DISPOSABLE.USER_DEVICE ADD CONSTRAINT FK_SYSTEM_USER_DEVICE_USER_DEVICE 
    FOREIGN KEY (USER_SID, DEVICE_SID)
    REFERENCES DISPOSABLE.SYSTEM_USER_DEVICE(USER_SID, DEVICE_SID)
;

ALTER TABLE DISPOSABLE.USER_DEVICE ADD CONSTRAINT FK_USER_USER_DEVICE 
    FOREIGN KEY (USER_SID)
    REFERENCES DISPOSABLE.USER(APP_SID)
;


