--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      c
-- Project :      disposable.dm1
-- Author :       Casey
--
-- Date Created : Thursday, September 05, 2013 00:28:35
-- Target DBMS : MySQL 5.x
--

-- 
-- TABLE: DISPOSABLE.APP 
--

CREATE TABLE DISPOSABLE.APP(
    APP_SID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (APP_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.AUTHORIZABLE_OBJECT 
--

CREATE TABLE DISPOSABLE.AUTHORIZABLE_OBJECT(
    APP_SID       INT UNSIGNED  NOT NULL,
    OBJECT_SID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (APP_SID, OBJECT_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.CLASS_PERMISSION 
--

CREATE TABLE DISPOSABLE.CLASS_PERMISSION(
    CLASS_TYPE_ID    INT    NOT NULL,
    PERMISSION_ID    INT    NOT NULL,
    PRIMARY KEY (CLASS_TYPE_ID, PERMISSION_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.CLASS_TYPE 
--

CREATE TABLE DISPOSABLE.CLASS_TYPE(
    CLASS_TYPE_ID    INT             NOT NULL,
    DESCRIPTION      VARCHAR(100)    NOT NULL,
    PRIMARY KEY (CLASS_TYPE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.CONSTANT 
--

CREATE TABLE DISPOSABLE.CONSTANT(
    SECTION    VARCHAR(30)     NOT NULL,
    NAME       VARCHAR(100)    NOT NULL,
    ID         INT             NOT NULL,
    CONSTRAINT CHK_CONSTANT_SECTION CHECK (SECTION = UPPER(TRIM(SECTION)) AND SECTION regexp '^[A-Za-z0-9_]+$'),
    CONSTRAINT CHK_CONSTANT_NAME CHECK (NAME = UPPER(TRIM(NAME)) AND NAME regexp '^[A-Za-z0-9_]+$'),
    PRIMARY KEY (SECTION, NAME)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.GROUP 
--

CREATE TABLE DISPOSABLE.GROUP(
    APP_SID      INT UNSIGNED  NOT NULL,
    GROUP_SID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (APP_SID, GROUP_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.GROUP_MEMBER 
--

CREATE TABLE DISPOSABLE.GROUP_MEMBER(
    APP_SID       INT UNSIGNED  NOT NULL,
    GROUP_SID     INT UNSIGNED  NOT NULL,
    MEMBER_SID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (APP_SID, GROUP_SID, MEMBER_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.PERMISSION 
--

CREATE TABLE DISPOSABLE.PERMISSION(
    PERMISSION_ID    INT             NOT NULL,
    DESCRIPTION      VARCHAR(100)    NOT NULL,
    PRIMARY KEY (PERMISSION_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.PERMISSION_SET 
--

CREATE TABLE DISPOSABLE.PERMISSION_SET(
    APP_SID                    INT UNSIGNED  NOT NULL,
    OBJECT_SID                 INT UNSIGNED  NOT NULL,
    AUTHORIZABLE_OBJECT_SID    INT UNSIGNED  NOT NULL,
    PERMISSION_ID              INT    NOT NULL,
    CLASS_TYPE_ID              INT    NOT NULL,
    PERMISSION_TYPE_ID         INT    NOT NULL,
    POSITION                   INT    NOT NULL,
    INHERITABLE                INT    NOT NULL,
    INHERITTED                 INT    NOT NULL,
    INHERIT_INHERITABLE        INT    NOT NULL,
    CONSTRAINT CHK_PERMISSION_SET_INHERITABLE CHECK (INHERITABLE in (0, 1)),
    CONSTRAINT CHK_PERMISSION_SET_INHERITTED CHECK (INHERITTED IN (0, 1)),
    CONSTRAINT CHK_PERMISSION_SET_INHERIT_INHERITABLE CHECK (INHERIT_INHERITABLE IN (0, 1)),
    PRIMARY KEY (APP_SID, OBJECT_SID, AUTHORIZABLE_OBJECT_SID, PERMISSION_ID, CLASS_TYPE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.PERMISSION_TYPE 
--

CREATE TABLE DISPOSABLE.PERMISSION_TYPE(
    PERMISSION_TYPE_ID    INT            NOT NULL,
    DESCRIPTION           VARCHAR(10)    NOT NULL,
    PRIMARY KEY (PERMISSION_TYPE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.SECURABLE_OBJECT 
--

CREATE TABLE DISPOSABLE.SECURABLE_OBJECT(
    OBJECT_SID           INT UNSIGNED  AUTO_INCREMENT,
    PARENT_OBJECT_SID    INT UNSIGNED,
    CLASS_TYPE_ID        INT    NOT NULL,
    PRIMARY KEY (OBJECT_SID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.SO_CLASS 
--

CREATE TABLE DISPOSABLE.SO_CLASS(
    OBJECT_SID       INT UNSIGNED  NOT NULL,
    CLASS_TYPE_ID    INT    NOT NULL,
    PRIMARY KEY (OBJECT_SID, CLASS_TYPE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.USER 
--

CREATE TABLE DISPOSABLE.USER(
    APP_SID     INT UNSIGNED  NOT NULL,
    USER_SID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (APP_SID, USER_SID)
)ENGINE=INNODB
;



-- 
-- INDEX: UK_SO_CLASS_OBJECT_SID 
--

CREATE UNIQUE INDEX UK_SO_CLASS_OBJECT_SID ON DISPOSABLE.SO_CLASS(OBJECT_SID)
;
-- 
-- TABLE: DISPOSABLE.APP 
--

ALTER TABLE DISPOSABLE.APP ADD CONSTRAINT FK_SECURABLE_OBJECT_APP 
    FOREIGN KEY (APP_SID)
    REFERENCES DISPOSABLE.SECURABLE_OBJECT(OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.AUTHORIZABLE_OBJECT 
--

ALTER TABLE DISPOSABLE.AUTHORIZABLE_OBJECT ADD CONSTRAINT FK_APP_AUTHORIZABLE_OBJECT 
    FOREIGN KEY (APP_SID)
    REFERENCES DISPOSABLE.APP(APP_SID)
;

ALTER TABLE DISPOSABLE.AUTHORIZABLE_OBJECT ADD CONSTRAINT FK_SECURABLE_OBJECT_AUTHORIZABLE_OBJECT 
    FOREIGN KEY (OBJECT_SID)
    REFERENCES DISPOSABLE.SECURABLE_OBJECT(OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.CLASS_PERMISSION 
--

ALTER TABLE DISPOSABLE.CLASS_PERMISSION ADD CONSTRAINT FK_CLASS_TYPE_CLASS_PERMISSION 
    FOREIGN KEY (CLASS_TYPE_ID)
    REFERENCES DISPOSABLE.CLASS_TYPE(CLASS_TYPE_ID)
;

ALTER TABLE DISPOSABLE.CLASS_PERMISSION ADD CONSTRAINT FK_PERMISSION_CLASS_PERMISSION 
    FOREIGN KEY (PERMISSION_ID)
    REFERENCES DISPOSABLE.PERMISSION(PERMISSION_ID)
;


-- 
-- TABLE: DISPOSABLE.GROUP 
--

ALTER TABLE DISPOSABLE.GROUP ADD CONSTRAINT FK_AUTHORIZABLE_OBJECT_GROUP 
    FOREIGN KEY (APP_SID, GROUP_SID)
    REFERENCES DISPOSABLE.AUTHORIZABLE_OBJECT(APP_SID, OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.GROUP_MEMBER 
--

ALTER TABLE DISPOSABLE.GROUP_MEMBER ADD CONSTRAINT FK_AUTHORIZABLE_OBJECT_GROUP_MEMBER 
    FOREIGN KEY (MEMBER_SID)
    REFERENCES DISPOSABLE.AUTHORIZABLE_OBJECT(OBJECT_SID)
;

ALTER TABLE DISPOSABLE.GROUP_MEMBER ADD CONSTRAINT FK_GROUP_GROUP_MEMBER 
    FOREIGN KEY (APP_SID, GROUP_SID)
    REFERENCES DISPOSABLE.GROUP(APP_SID, GROUP_SID)
;


-- 
-- TABLE: DISPOSABLE.PERMISSION_SET 
--

ALTER TABLE DISPOSABLE.PERMISSION_SET ADD CONSTRAINT FK_AUTHORIZABLE_OBJECT_PERMISSION_SET 
    FOREIGN KEY (APP_SID, AUTHORIZABLE_OBJECT_SID)
    REFERENCES DISPOSABLE.AUTHORIZABLE_OBJECT(APP_SID, OBJECT_SID)
;

ALTER TABLE DISPOSABLE.PERMISSION_SET ADD CONSTRAINT FK_CLASS_PERMISSION_PERMISSION_SET 
    FOREIGN KEY (PERMISSION_ID, CLASS_TYPE_ID)
    REFERENCES DISPOSABLE.CLASS_PERMISSION(CLASS_TYPE_ID, PERMISSION_ID)
;

ALTER TABLE DISPOSABLE.PERMISSION_SET ADD CONSTRAINT FK_PERMISSION_TYPE_PERMISSION_SET 
    FOREIGN KEY (PERMISSION_TYPE_ID)
    REFERENCES DISPOSABLE.PERMISSION_TYPE(PERMISSION_TYPE_ID)
;

ALTER TABLE DISPOSABLE.PERMISSION_SET ADD CONSTRAINT FK_SO_CLASS_PERMISSION_SET 
    FOREIGN KEY (OBJECT_SID, CLASS_TYPE_ID)
    REFERENCES DISPOSABLE.SO_CLASS(OBJECT_SID, CLASS_TYPE_ID)
;


-- 
-- TABLE: DISPOSABLE.SECURABLE_OBJECT 
--

ALTER TABLE DISPOSABLE.SECURABLE_OBJECT ADD CONSTRAINT FK_CLASS_TYPE_SECURABLE_OBJECT 
    FOREIGN KEY (CLASS_TYPE_ID)
    REFERENCES DISPOSABLE.CLASS_TYPE(CLASS_TYPE_ID)
;

ALTER TABLE DISPOSABLE.SECURABLE_OBJECT ADD CONSTRAINT FK_SECURABLE_OBJECT_SECURABLE_OBJECT 
    FOREIGN KEY (PARENT_OBJECT_SID)
    REFERENCES DISPOSABLE.SECURABLE_OBJECT(OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.SO_CLASS 
--

ALTER TABLE DISPOSABLE.SO_CLASS ADD CONSTRAINT FK_CLASS_TYPE_SO_CLASS 
    FOREIGN KEY (CLASS_TYPE_ID)
    REFERENCES DISPOSABLE.CLASS_TYPE(CLASS_TYPE_ID)
;

ALTER TABLE DISPOSABLE.SO_CLASS ADD CONSTRAINT FK_SECURABLE_OBJECT_SO_CLASS 
    FOREIGN KEY (OBJECT_SID)
    REFERENCES DISPOSABLE.SECURABLE_OBJECT(OBJECT_SID)
;


-- 
-- TABLE: DISPOSABLE.USER 
--

ALTER TABLE DISPOSABLE.USER ADD CONSTRAINT FK_AUTHORIZABLE_OBJECT_USER 
    FOREIGN KEY (APP_SID, USER_SID)
    REFERENCES DISPOSABLE.AUTHORIZABLE_OBJECT(APP_SID, OBJECT_SID)
;


