--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      c
-- Project :      disposable.dm1
-- Author :       Casey
--
-- Date Created : Monday, September 02, 2013 23:23:40
-- Target DBMS : MySQL 5.x
--

-- 
-- TABLE: DISPOSABLE.ACT 
--

CREATE TABLE DISPOSABLE.ACT(
    APP_ID         INT UNSIGNED  NOT NULL,
    ACT_ID         CHAR(36)    NOT NULL,
    ACT_TYPE_ID    INT         NOT NULL,
    USER_ID        INT UNSIGNED  NOT NULL,
    DEVICE_ID      INT UNSIGNED  NOT NULL,
    ISSUED_DTM     DATETIME    NOT NULL,
    PRIMARY KEY (APP_ID, ACT_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.ACT_TYPE 
--

CREATE TABLE DISPOSABLE.ACT_TYPE(
    ACT_TYPE_ID          INT         NOT NULL,
    EXPIRATION_OFFSET    DATETIME    NOT NULL,
    PRIMARY KEY (ACT_TYPE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.APP 
--

CREATE TABLE DISPOSABLE.APP(
    APP_ID         INT UNSIGNED    AUTO_INCREMENT,
    HOST           VARCHAR(200)    NOT NULL,
    SECURE_ONLY    INT             DEFAULT 1 NOT NULL
                   CHECK (SECURE_ONLY IN (0, 1)),
    PRIMARY KEY (APP_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.DEVICE 
--

CREATE TABLE DISPOSABLE.DEVICE(
    APP_ID            INT UNSIGNED    NOT NULL,
    DEVICE_ID         INT UNSIGNED    NOT NULL,
    DEVICE_TYPE_ID    INT             NOT NULL,
    USER_ID           INT UNSIGNED    NOT NULL,
    NAME              VARCHAR(100)    NOT NULL,
    PRIMARY KEY (APP_ID, DEVICE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.DEVICE_SEED 
--

CREATE TABLE DISPOSABLE.DEVICE_SEED(
    DEVICE_ID    INT UNSIGNED  AUTO_INCREMENT,
    PRIMARY KEY (DEVICE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.DEVICE_TYPE 
--

CREATE TABLE DISPOSABLE.DEVICE_TYPE(
    DEVICE_TYPE_ID         INT    NOT NULL,
    DEFAULT_ACT_TYPE_ID    INT    NOT NULL,
    PRIMARY KEY (DEVICE_TYPE_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.USER 
--

CREATE TABLE DISPOSABLE.USER(
    APP_ID     INT UNSIGNED  NOT NULL,
    USER_ID    INT UNSIGNED  NOT NULL,
    PRIMARY KEY (APP_ID, USER_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.USER_SEED 
--

CREATE TABLE DISPOSABLE.USER_SEED(
    USER_ID    INT UNSIGNED  AUTO_INCREMENT,
    PRIMARY KEY (USER_ID)
)ENGINE=INNODB
;



-- 
-- TABLE: DISPOSABLE.ACT 
--

ALTER TABLE DISPOSABLE.ACT ADD CONSTRAINT FK_ACT_TYPE_ACT 
    FOREIGN KEY (ACT_TYPE_ID)
    REFERENCES DISPOSABLE.ACT_TYPE(ACT_TYPE_ID)
;

ALTER TABLE DISPOSABLE.ACT ADD CONSTRAINT FK_APP_ACT 
    FOREIGN KEY (APP_ID)
    REFERENCES DISPOSABLE.APP(APP_ID)
;

ALTER TABLE DISPOSABLE.ACT ADD CONSTRAINT FK_DEVICE_ACT 
    FOREIGN KEY (APP_ID, DEVICE_ID)
    REFERENCES DISPOSABLE.DEVICE(APP_ID, DEVICE_ID)
;

ALTER TABLE DISPOSABLE.ACT ADD CONSTRAINT FK_USER_ACT 
    FOREIGN KEY (APP_ID, USER_ID)
    REFERENCES DISPOSABLE.USER(APP_ID, USER_ID)
;


-- 
-- TABLE: DISPOSABLE.DEVICE 
--

ALTER TABLE DISPOSABLE.DEVICE ADD CONSTRAINT FK_APP_DEVICE 
    FOREIGN KEY (APP_ID)
    REFERENCES DISPOSABLE.APP(APP_ID)
;

ALTER TABLE DISPOSABLE.DEVICE ADD CONSTRAINT FK_DEVICE_SEED_DEVICE 
    FOREIGN KEY (DEVICE_ID)
    REFERENCES DISPOSABLE.DEVICE_SEED(DEVICE_ID)
;

ALTER TABLE DISPOSABLE.DEVICE ADD CONSTRAINT FK_DEVICE_TYPE_DEVICE 
    FOREIGN KEY (DEVICE_TYPE_ID)
    REFERENCES DISPOSABLE.DEVICE_TYPE(DEVICE_TYPE_ID)
;

ALTER TABLE DISPOSABLE.DEVICE ADD CONSTRAINT FK_USER_DEVICE 
    FOREIGN KEY (APP_ID, USER_ID)
    REFERENCES DISPOSABLE.USER(APP_ID, USER_ID)
;


-- 
-- TABLE: DISPOSABLE.DEVICE_TYPE 
--

ALTER TABLE DISPOSABLE.DEVICE_TYPE ADD CONSTRAINT FK_ACT_TYPE_DEVICE_TYPE 
    FOREIGN KEY (DEFAULT_ACT_TYPE_ID)
    REFERENCES DISPOSABLE.ACT_TYPE(ACT_TYPE_ID)
;


-- 
-- TABLE: DISPOSABLE.USER 
--

ALTER TABLE DISPOSABLE.USER ADD CONSTRAINT FK_APP_USER 
    FOREIGN KEY (APP_ID)
    REFERENCES DISPOSABLE.APP(APP_ID)
;

ALTER TABLE DISPOSABLE.USER ADD CONSTRAINT FK_USER_SEED_USER 
    FOREIGN KEY (USER_ID)
    REFERENCES DISPOSABLE.USER_SEED(USER_ID)
;


